import type { Metadata } from "next";
import { Lexend, Overpass_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import { OnboardingProvider } from "@onboardjs/react";
import { demoOnboardingSteps } from "@/config/onboardingConfig";

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexend.variable} antialiased font-lexend`}>
        <OnboardingProvider
          steps={demoOnboardingSteps}
          // Enable localStorage persistence for this demo
          localStoragePersistence={{
            key: "onboardjsDemo_v1_progress",
            ttl: 1000 * 60 * 60 * 24,
          }}
        >
          {children}
        </OnboardingProvider>
        <Toaster />
      </body>
    </html>
  );
}
