name: 'Release Workflow'
description: 'Publish package to NPM and create a GitHub release'

inputs:
    package_path:
        description: 'Package path to publish'
        required: true
    package_name:
        description: 'Package name to publish'
        required: true
    package_version:
        description: 'Package version to publish'
        required: true
    npm_token:
        description: 'NPM token to publish package'
        required: true
    github_token:
        description: 'GitHub token to create release'
        required: true

runs:
    using: 'composite'
    steps:
        - name: Set up Git
          run: |
              git config user.name "github-actions[bot]"
              git config user.email "github-actions[bot]@users.noreply.github.com"
          shell: bash

        - name: Install pnpm
          uses: pnpm/action-setup@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
              node-version: '22'
              registry-url: https://registry.npmjs.org

        - name: Install dependencies
          shell: bash
          run: pnpm install --frozen-lockfile

        - name: Build package
          shell: bash
          run: pnpm build

        - name: Tag repository with package_name and package_version
          shell: bash
          run: |
              git tag -a "${{ inputs.package_name }}@${{ inputs.package_version }}" -m "${{ inputs.package_name }}@${{ inputs.package_version }}"

        - name: Publish package to NPM
          shell: bash
          run: |
              pnpm publish --filter=${{ inputs.package_name }} --access public
          env:
              NODE_AUTH_TOKEN: ${{ inputs.npm_token }}

        - name: Push tag to GitHub
          shell: bash
          run: |
              git push origin "${{ inputs.package_name }}@${{ inputs.package_version }}"

        - name: Create GitHub release
          working-directory: ${{ inputs.package_path }}
          shell: bash
          env:
              GH_TOKEN: ${{ inputs.github_token }}
          run: |
              # Check if CHANGELOG.md exists and read from it, otherwise use a default message
              if [ -f "CHANGELOG.md" ]; then
                  LAST_CHANGELOG_ENTRY=$(awk -v defText="see CHANGELOG.md" '/^## /{if (flag) exit; flag=1} flag && /^##$/{exit} flag; END{if (!flag) print defText}' CHANGELOG.md)
              else
                  LAST_CHANGELOG_ENTRY="Release ${{ inputs.package_version }} of ${{ inputs.package_name }}. See the repository for more details."
              fi

              # Create GitHub release
              gh api \
                --method POST \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                /repos/Somafet/onboardjs/releases \
                -f tag_name="${{ inputs.package_name }}@${{ inputs.package_version }}" \
              -f target_commitish='main' \
              -f name="${{ inputs.package_name }}@${{ inputs.package_version }}" \
              -f body="$LAST_CHANGELOG_ENTRY" \
              -F draft=false \
              -F prerelease=false \
              -F generate_release_notes=false

        - name: Remove consumed changesets
          shell: bash
          run: |
              # Remove all changeset files
              find .changeset -maxdepth 1 -name "*.md" ! -name "README.md" -delete

              # Stage and commit the changes
              git add .changeset

              # Commit only if there are changes
              if ! git diff --cached --quiet; then
                  git commit -m "chore: remove consumed changesets for ${{ inputs.package_name }}@${{ inputs.package_version }}"
                  # Pull latest changes before pushing to handle concurrent publishes
                  git pull origin main --rebase
                  git push origin main
              fi
